### ISSUE TITLE
`package.json` uses invalid semver range syntax, rendering it uninstallable

### ISSUE THREAD

**Issue by rsek** [Mavrin/stylelint-declaration-use-css-custom-properties#18]
currently the semver for[ the `stylelint` peer dependency entry](https://github.com/Mavrin/stylelint-declaration-use-css-custom-properties/blob/17c0f73aa34a459a3f1b332db1e3f6ef9390db73/package.json#L35) has a typo, `^14 | ^15`. its semver tool reports it as invalid: https://semver.npmjs.com/

changing it to `^14 || ^15`  or `14 - 15` ought to resolve the issue :)

**Comment by Mavrin** [comment]
thanks. Fixed.
